// Prompt builders for Task 6.1 — Full RFP Generator
//
// Each of the 10 sections is generated by a separate Claude call.
// This lets individual sections be regenerated without touching others.
//
// Context passed to every section prompt:
// - brief.extracted_data (all 12 fields — study_objective is safe to include
//   in an RFP; compound name/MOA/indication were stripped at extraction time)
// - rfp_context_notes (curated items from meeting debriefs, marked by the user)
// - engagement thread summaries (last 5 messages from each CRO conversation)
// - company settings (name, contact)
// - rfp_id (unique human-readable identifier)

export const SECTION_KEYS = [
  's1_header',
  's2_overview',
  's3_scope',
  's4_regulatory',
  's5_deliverables',
  's6_proposal_reqs',
  's7_eval_criteria',
  's8_timeline',
  's9_terms',
  's10_contact',
] as const;

export type SectionKey = (typeof SECTION_KEYS)[number];

export const SECTION_META: Record<SectionKey, { label: string; description: string; maxTokens: number }> = {
  s1_header:        { label: '1. RFP Header',                    description: 'RFP ID, issue date, company name, contact details',                    maxTokens: 300  },
  s2_overview:      { label: '2. Study Overview',                 description: 'Study objective and scientific background (1 paragraph)',               maxTokens: 500  },
  s3_scope:         { label: '3. Scope of Work',                  description: 'Full technical requirements — the most detailed section',               maxTokens: 1000 },
  s4_regulatory:    { label: '4. Regulatory Requirements',        description: 'GLP, compliance framework, report standards',                          maxTokens: 400  },
  s5_deliverables:  { label: '5. Deliverables',                   description: 'Exact list with format and due dates',                                  maxTokens: 400  },
  s6_proposal_reqs: { label: '6. Proposal Requirements',          description: 'What the CRO response must contain',                                   maxTokens: 400  },
  s7_eval_criteria: { label: '7. Evaluation Criteria',            description: 'How the biotech will score CRO responses',                             maxTokens: 350  },
  s8_timeline:      { label: '8. Proposal Timeline',              description: 'Submission deadline, Q&A deadline, award date',                        maxTokens: 300  },
  s9_terms:         { label: '9. Terms & Confidentiality',        description: 'NDA reminder, IP/data ownership clause',                               maxTokens: 350  },
  s10_contact:      { label: '10. Contact & Submission',          description: 'Contact details and submission instructions',                          maxTokens: 250  },
};

// ── Shared context builder ────────────────────────────────────────────────────

export interface RfpContext {
  rfpId:            string;
  companyName:      string;
  contactName:      string;
  contactEmail:     string;
  issueDate:        string;
  extractedData:    Record<string, { value: string | null; tag: string }>;
  rfpContextNotes:  { text: string; type: string; source_cro_name: string }[];
  threadSummaries:  { cro_name: string; summary: string }[];
}

function buildSharedContext(ctx: RfpContext): string {
  const fields = ctx.extractedData;

  const briefLines = [
    fields.study_objective?.value    && `Study objective: ${fields.study_objective.value}`,
    fields.study_type?.value         && `Study type: ${fields.study_type.value}`,
    fields.assay_types?.value        && `Assay types: ${fields.assay_types.value}`,
    fields.compound_description?.value && `Compound description: ${fields.compound_description.value}`,
    fields.species_model?.value      && `Species/model: ${fields.species_model.value}`,
    fields.group_sizes?.value        && `Group sizes: ${fields.group_sizes.value}`,
    fields.primary_endpoints?.value  && `Primary endpoints: ${fields.primary_endpoints.value}`,
    fields.timeline?.value           && `Timeline: ${fields.timeline.value}`,
    fields.glp_requirement?.value    && `GLP requirement: ${fields.glp_requirement.value}`,
    fields.deliverables?.value       && `Key deliverables: ${fields.deliverables.value}`,
    fields.budget_range?.value       && `Budget range: ${fields.budget_range.value}`,
    fields.special_requirements?.value && `Special requirements: ${fields.special_requirements.value}`,
  ].filter(Boolean).join('\n');

  const refinements = ctx.rfpContextNotes
    .filter(n => n.type === 'rfp_refinement')
    .map(n => `- [from ${n.source_cro_name}] ${n.text}`)
    .join('\n');

  const openQuestions = ctx.rfpContextNotes
    .filter(n => n.type === 'open_question')
    .map(n => `- [from ${n.source_cro_name}] ${n.text}`)
    .join('\n');

  const threads = ctx.threadSummaries
    .map(t => `${t.cro_name}: ${t.summary}`)
    .join('\n\n');

  return `
STUDY BRIEF:
${briefLines || '(No structured brief data available)'}

REFINEMENTS FROM CRO MEETINGS (must be reflected in RFP content):
${refinements || '(none)'}

GAPS STILL OPEN (mark as [TO BE SPECIFIED] where relevant):
${openQuestions || '(none)'}

CRO ENGAGEMENT CONTEXT:
${threads || '(no prior CRO correspondence)'}

RFP METADATA:
- RFP ID: ${ctx.rfpId}
- Issue date: ${ctx.issueDate}
- Issuing company: ${ctx.companyName}
- Contact: ${ctx.contactName} <${ctx.contactEmail}>
`.trim();
}

// ── Per-section prompt builders ───────────────────────────────────────────────

const SYSTEM_PROMPT = `You are an expert preclinical study RFP writer helping a biotech company communicate study requirements to Contract Research Organisations. Write formally and precisely. Use [TO BE SPECIFIED] for any required content that is genuinely unknown — never invent data. Do not use generic filler sentences.`;

export function buildSectionPrompt(section: SectionKey, ctx: RfpContext): string {
  const shared = buildSharedContext(ctx);
  const co = ctx.companyName;
  const rfpId = ctx.rfpId;

  const instructions: Record<SectionKey, string> = {
    s1_header: `
Write Section 1: RFP Header for a preclinical study RFP.
Format as a clean header block (not a table) with these fields on separate lines:
  RFP ID: ${rfpId}
  Issue Date: ${ctx.issueDate}
  Issuing Company: ${co}
  Contact: ${ctx.contactName} | ${ctx.contactEmail}
  Classification: Confidential
  Purpose: Preclinical [study type] study — Request for Proposal
Do not add any prose paragraphs. Just the header block.`,

    s2_overview: `
Write Section 2: Study Overview.
Two paragraphs maximum:
1. State the study objective in scientific terms. Do NOT mention compound name, MOA, or disease indication.
   Use the study_objective and study_type from the brief.
2. Brief scientific rationale for why this type of study is needed (generic — not compound-specific).
If study_objective is [MISSING], write: "[TO BE SPECIFIED — study objective not yet defined]"`,

    s3_scope: `
Write Section 3: Scope of Work.
This is the most detailed section. Cover ALL of the following sub-sections using the brief data:
3.1 Study Design — species, group sizes, dosing route, duration, cohort structure
3.2 Test Article — describe only as drug class + route (e.g. "small molecule, oral") — NEVER compound name
3.3 Study Endpoints — primary and secondary endpoints
3.4 Assay Requirements — specific assays, methods, instrumentation
3.5 GLP/Regulatory Framework — compliance level required
3.6 Special Requirements — any constraints, preferences, or exclusions from the brief

For any sub-section where data is MISSING, write [TO BE SPECIFIED].
Apply all RFP refinements from CRO meetings to the relevant sub-sections.
Be specific and actionable — this section drives CRO costing.`,

    s4_regulatory: `
Write Section 4: Regulatory Requirements.
Cover:
- GLP compliance level (GLP-compliant / non-GLP exploratory / IND-enabling)
- Applicable regulatory guidelines (e.g. OECD, ICH, EPA)
- Study report format requirements (e.g. SEND dataset, PDF, raw data)
- Archival requirements if applicable
Base on the glp_requirement and deliverables fields. Mark any unknowns as [TO BE SPECIFIED].`,

    s5_deliverables: `
Write Section 5: Deliverables.
Provide a numbered list of all required deliverables. For each, specify:
- What the deliverable is
- The format required (e.g. PDF report, electronic raw data, SEND dataset)
- Indicative due date relative to study completion (e.g. "Draft report: within 4 weeks of study completion")
Base on deliverables field and any refinements from CRO meetings.
If timeline is known, include absolute deadlines where possible.`,

    s6_proposal_reqs: `
Write Section 6: Proposal Requirements.
List exactly what the CRO's proposal response must contain. Standard items:
1. Technical approach and study design confirmation
2. Deviations from scope (if any)
3. Staffing plan: Study Director and key personnel CVs
4. Facility information: GLP certification status, relevant accreditations
5. Detailed project timeline (Gantt or milestone list)
6. Itemised budget with payment schedule
7. Quality assurance plan
8. References / prior work examples for this study type
Format as a numbered list. Add any study-specific requirements from the brief.`,

    s7_eval_criteria: `
Write Section 7: Evaluation Criteria.
Explain how ${co} will score CRO proposals. Use a weighted criteria list:
- Technical capability and experience (40%)
- Price and value (25%)
- Timeline and capacity (20%)
- Quality systems and compliance (15%)
Adjust weights slightly if brief data suggests a particular priority (e.g. GLP compliance is critical → upweight quality).
State that ${co} reserves the right to request presentations or site visits.`,

    s8_timeline: `
Write Section 8: Proposal Timeline.
Provide a milestone table with these rows (fill in realistic dates based on the timeline field; use [TO BE SPECIFIED] if unknown):
- RFP Issue Date
- CRO Questions Deadline (suggest: 5 business days after issue)
- ${co} Response to Questions (suggest: 3 business days after questions deadline)
- Proposal Submission Deadline (suggest: 10 business days after RFP issue)
- Shortlist Notification
- Study Award / Contract Execution
- Target Study Start Date
Format as a simple list (not a table) — one milestone per line.`,

    s9_terms: `
Write Section 9: Terms and Confidentiality.
Cover:
1. Confidentiality: Remind the CRO that all information in this RFP is confidential. A mutual NDA must be in place before study award. Do not disclose to third parties.
2. IP ownership: All data, results, and reports generated under this study are the sole property of ${co}.
3. No obligation: Receipt of this RFP does not obligate ${co} to award a contract.
4. Compliance: The CRO must comply with all applicable regulations and ${co}'s quality requirements.
Keep to 3-4 short paragraphs. Formal but not legal-document dense.`,

    s10_contact: `
Write Section 10: Contact and Submission Instructions.
Include:
- Who to contact for questions: ${ctx.contactName}, ${ctx.contactEmail}
- How to submit the proposal (email to same contact)
- File format requirements (PDF preferred, clearly labelled)
- Naming convention: "[CRO Name] — Proposal — ${rfpId}"
- Confirmation of receipt: ask CRO to acknowledge receipt by reply email within 2 business days
Keep concise — 1 short paragraph.`,
  };

  return `${instructions[section]}

--- STUDY CONTEXT ---
${shared}

Return ONLY the section text — no section number header (we add that in the UI), no preamble, no closing remarks. Write in formal RFP prose unless a list format is specified.`;
}
